### ISSUE TITLE
horizontal scrollbar should be attached to the view thingy

### ISSUE THREAD

**Issue by DetachHead** [mschleeweiss/ui5-good-batch#5]
when a batch request is really long i have to scroll all the way down to the bottom to access the horizontal scroll bar:

![image](https://user-images.githubusercontent.com/57028336/168007632-76b42c2b-570c-4c89-a113-1c7a8a70e852.png)
![image](https://user-images.githubusercontent.com/57028336/168007715-3ab9f6fd-24e5-4cd5-9814-33cb2814e8ff.png)

it would be more convenient if it was like on the "network" tab, where both scroll bars are always visible:
![image](https://user-images.githubusercontent.com/57028336/168007954-f7c84b6c-5fe3-456b-843c-94939e56d1c3.png)

**Comment by mschleeweiss** [comment]
Hey @DetachHead ,

thanks for opening all these issues. I paused development when I realised that the official [UI5 Inspector](https://chrome.google.com/webstore/detail/ui5-inspector/bebecogbafbighhaildooiibipcnbngo?hl=de) has a very similar functionality. 

Do you mind checking if this extension solves your needs? Maybe it might make more sense for me to provide new features (or a better UI) to the official extension than having two extensions which do almost the same.

**Comment by DetachHead** [comment]
yeah i tried that extension before but it was pretty much unusable to me due to https://github.com/SAP/ui5-inspector/issues/168, but it looks like they fixed that so i'll give it another go

it may be worth adding a notice to the readme stating that this extension is no longer under development and directing users to the official one?

**Comment by mschleeweiss** [comment]
Hello @DetachHead , thanks for your suggestion. I updated the readme and will archive this repository. Once again thanks for suggesting these improvements, would have loved to see them come to life. But I will try to invest some free time into the UI5 inspector.
